enum MODES {
  SPECIAL_SERVICE = 0,
  CLOSED = 1,
  SUSPENDED = 2,
  PART_SUSPENDED = 3,
  PLANNED_CLOSURE = 4,
  PART_CLOSURE = 5,
  SEVERE_DELAYS = 6,
  REDUCED_SERVICE = 7,
  BUS_SERVICE = 8,
  MINOR_DELAYS = 9,
  GOOD_SERVICE = 10,
  PART_CLOSED = 11,
  NOT_RUNNING = 16,
  SERVICE_CLOSED = 20
}

export default MODES;